// angular/src/app/views/home/home.component.ts
import { Component, OnInit, Input } from "@angular/core"

@Component({
  selector: "app-home",
  templateUrl: "./home.component.html",
  styleUrls: ["./home.component.css"],
})
export class HomeComponent implements OnInit {
  @Input() msg: string | undefined
  legenda: string = "Estou no Angular"

  constructor() {}

  ngOnInit(): void {
    throw new Error("Method not implemented.")
  }

  resetLegenda(): void {
    this.legenda = "Estou no Angular"
  }
}

<h1>{{ msg }}</h1>
<h2>{{ legenda }}</h2>

<input type="text" [(ngModel)]="legenda" />

<button (click)="resetLegenda()">Reset Legenda</button>

// react-/src/views/home/Home.jsx
import React, { useState } from "react"

const Home = (props) => {
  // const legenda = useState("Estou no React") retorna array
  const [legenda, setLegenda] = useState("Estou no React")

  const resetLegenda = () => {
    setLegenda("Estou no React")
  }

  return (
    <>
      <h1>{props.msg}</h1>
      <h2>{legenda}</h2>

      <input
        type="text"
        value={legenda}
        onChange={(event) => setLegenda(event.target.value)}
      />

      <button onClick={resetLegenda}>Reset Legenda</button>
    </>
  )
}

export default Home
